In [1]:
# Import plotting tool
import matplotlib.pyplot as plt

# Import classifiers
from sklearn.neighbors import KNeighborsClassifier

# Import datasets and performance metrics
from sklearn import datasets, metrics

# The digits dataset
digits = datasets.load_digits()

In [2]:
images_and_labels = list(zip(digits.images, digits.target))
for index, (image, label) in enumerate(images_and_labels[:4]):
    plt.subplot(2, 4, index + 1)
    plt.axis('off')
    plt.imshow(image, cmap=plt.cm.gray_r, interpolation='nearest')
    plt.title('Training: %i' % label)

In [3]:
# To apply a classifier on this data, we need to flatten the image, to
# turn the data in a (samples, feature) matrix:
(n_samples, width, height) = digits.images.shape
#data = digits.images.reshape(n_samples, -1)
data = digits.images.reshape(n_samples, width * height)

In [4]:
# Create a classifier: a K Neighbors Classifier classifier
classifier = KNeighborsClassifier(n_neighbors=13)

In [5]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, digits.target, train_size=0.6)

In [6]:
# We learn the digits on the first 60% of the digits
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=13, p=2,
           weights='uniform')

In [7]:
# Now predict the value of the digit on the remaining
expected = y_test
predicted = classifier.predict(X_test)

In [8]:
print("Classification report for classifier %s:\n%s\n"
      % (classifier, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))

Classification report for classifier KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=13, p=2,
           weights='uniform'):
             precision    recall  f1-score   support

          0       0.98      1.00      0.99        64
          1       0.92      1.00      0.96        72
          2       1.00      0.97      0.99        77
          3       0.99      0.99      0.99        67
          4       1.00      0.99      0.99        73
          5       0.96      0.97      0.97        73
          6       0.97      1.00      0.99        71
          7       0.99      1.00      0.99        78
          8       0.94      0.93      0.93        68
          9       0.99      0.89      0.94        76

avg / total       0.97      0.97      0.97       719


Confusion matrix:
[[64  0  0  0  0  0  0  0  0  0]
 [ 0 72  0  0  0  0  0  0  0  0]
 [ 0  1 75  0  0  0  0  0  1  0]
 [ 0  0  0 66  0  0  0  0  1  0]
 [ 0  0

In [9]:
images_and_predictions = list(zip(X_test.reshape(len(X_test),width,height), predicted))
for index, (image, prediction) in enumerate(images_and_predictions[:4]):
    plt.subplot(2, 4, index + 5)
    plt.axis('off')
    plt.imshow(image, cmap=plt.cm.gray_r, interpolation='nearest')
    plt.title('Prediction: %i' % prediction)

plt.show()